sudo: required # Everytime we use docker we need sudo permissions
language: generic
services:
  - docker # We need a copy of docker
before_install:
  - docker build -t mbeiswenger/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true mbeiswenger/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-722610766895"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
